version: '3.8'

services:

  db:    
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: agatinet/foodgram_backend:v1
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/backend/staticfiles/
      - media_value:/app/backend/media/
    env_file:
      - ./.env

  frontend:
    image: agatinet/foodgram_front:v1
    volumes:
      - result_build:/app/result_build/build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - ../backend/api/static/api/:/usr/share/nginx/html/api/docs/
      
    depends_on:
      - backend

volumes:
  result_build:
  postgres_data:
  static_value:
  media_value:
