version: '3.8'

services:
  db:    
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env  

  backend:
    image: agatinet/foodgram_backend:v1
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - static_data:/app/static/
      - media_data:/app/media/
    env_file:
      - ./.env

  frontend:
    image: agatinet/foodgram_frontend:v1
    depends_on:
      - backend
    volumes:
      - frontend_build:/app/result_build/build/

  nginx:
    image: nginx:1.21.3-alpine
    depends_on:
      - backend
    restart: unless-stopped    
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/var/html/static/
      - media_data:/var/html/media/
      - frontend_build:/usr/share/nginx/html/
      - nginx_log:/var/log/nginx/
    ports:
      - "$PORT:80"
      - "$SSL_PORT:443"    
    env_file:
      - ./.env

volumes:
  static_data:
  media_data:
  postgres_db:
  frontend_build:
  nginx_log:
