# Generated by Django 2.2.16 on 2022-09-15 11:10

import colorfield.fields
import django.core.validators
from django.db import migrations
import re


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', error_messages={'unique': 'A tag with that color already exists.'}, help_text='Required. Enter HEX-code color, please.', image_field=None, max_length=7, samples=None, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'), 'The valid hexadecimal color code must satisfy the following conditions:1. It should start from ‘#’ symbol.2. It should be followed by the letters from a-f, A-F and/or digits from 0-9.3. The length of the hexadecimal color code should be either 6 or 3, excluding ‘#’ symbol.', 'invalid')], verbose_name='color HEX-code'),
        ),
    ]
