# Generated by Django 2.2.16 on 2022-09-16 12:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220915_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Minimum cooking time 1 minute')], verbose_name='cooking time (minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='public date'),
        ),
    ]
