# Generated by Django 2.2.16 on 2022-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220916_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Required. Enter name recipe, please.', max_length=500, verbose_name='name'),
        ),
    ]
