# Generated by Django 2.2.16 on 2022-09-06 13:47

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220906_1643'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_user_subscribers',
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='check_not_loop_user_subscribed',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('subscribed__from_customuser_id', 'subscribed__to_customuser_id'), name='unique_user_subscribers'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, subscribed__from_customuser_id=django.db.models.expressions.F('subscribed__to_customuser_id')), name='check_not_loop_user_subscribed'),
        ),
    ]
