# Generated by Django 2.2.16 on 2022-10-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220921_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-date_subscriber'], 'verbose_name': 'subscriber', 'verbose_name_plural': 'subscribers'},
        ),
    ]
