# Generated by Django 2.2.16 on 2022-09-06 13:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220906_1647'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_user_subscribers',
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='check_not_loop_user_subscribed',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('subscribed_from_customuser', 'subscribed_to_customuser'), name='unique_user_subscribers'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, subscribed__from_customuser=django.db.models.expressions.F('subscribed_to_customuser_id')), name='check_not_loop_user_subscribed'),
        ),
    ]
