# Generated by Django 2.2.16 on 2022-09-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220906_1653'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='check_not_loop_user_subscribed',
        ),
    ]
