# Generated by Django 2.2.16 on 2022-09-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220906_1654'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_user_subscribers',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('subscribed__from_customuser', 'subscribed__to_customuser'), name='unique_user_subscribers'),
        ),
    ]
